markdown: rdiscount
pygments: true

name: <a href="http://domenika.leto.net">Duke Leto + Lady Domenika</a>
email: duke@leto.net
tagline: "Doing It In The Name Of Science"
location: Portland, OR
freeyourself_url: http://github.com/letolabs/freeyourself

gallery_base: http://dukeleto.openphoto.s3-website-us-east-1.amazonaws.com
