markdown: rdiscount
pygments: true

name: Duke Leto + Lady Domenika
email: domenathon@leto.net
tagline: "Doing It In The Name Of Science"
location: Portland, OR
freeyourself_url: http://github.com/letolabs/freeyourself
